// <auto-generated />
using System;
using DessertsMakery.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DessertsMakery.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.Consumable", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackaging", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumableId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasuringId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MeasuringValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("ConsumableId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("MeasuringId");

                    b.ToTable("ConsumablePackagings");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingImage", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumablePackagingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("ConsumablePackagingId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("ConsumablePackagingImages");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingPrice", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumablePackagingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ConsumablePackagingId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("ConsumablePackagingPrices");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Customers.Customer", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamily", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("DessertFamilies");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamilyWeight", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("DessertFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DessertWeightId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("DessertFamilyId");

                    b.HasIndex("DessertWeightId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("DessertFamilyWeights");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertPricing", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("DessertFamilyWeightId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("DessertFamilyWeightId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("DessertPricings");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertTemplate", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long?>("DessertFamilyInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DessertFamilyWeightId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("DessertFamilyInternalId");

                    b.HasIndex("DessertFamilyWeightId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("DessertTemplates");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertTemplateRecipe", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("DessertTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("DessertTemplateId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("DessertTemplateRecipes");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertWeight", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasuringId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MeasuringValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("MeasuringId");

                    b.ToTable("DessertWeights");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Component", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasuringId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Proportion")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("MeasuringId");

                    b.HasIndex("ParentId");

                    b.ToTable("Components");

                    b.HasDiscriminator<string>("ComponentType").HasValue("Component");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.ComponentMeasuringConversion", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasuringId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("MeasuringId");

                    b.ToTable("ComponentMeasuringConversion");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Measuring", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Measurings");

                    b.HasData(
                        new
                        {
                            InternalId = 2L,
                            CreatedAt = new DateTime(2024, 3, 6, 11, 36, 17, 505, DateTimeKind.Utc).AddTicks(9910),
                            ExternalId = new Guid("0685a1f7-c185-4045-b158-3ee72128d2cb"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 3, 6, 11, 36, 17, 505, DateTimeKind.Utc).AddTicks(9910),
                            Name = "Mass"
                        },
                        new
                        {
                            InternalId = 1L,
                            CreatedAt = new DateTime(2024, 3, 6, 11, 36, 17, 505, DateTimeKind.Utc).AddTicks(9924),
                            ExternalId = new Guid("baf0dd1d-d24d-42a1-a112-e2bb55f6eeae"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(2024, 3, 6, 11, 36, 17, 505, DateTimeKind.Utc).AddTicks(9924),
                            Name = "Quantity"
                        });
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.CustomDiscount", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("CustomDiscounts");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.CustomPrice", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("CustomPrices");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.Order", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<DateTime>("ReceivingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItem", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("DessertTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("DessertTemplateId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemDetailsId")
                        .IsUnique();

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailPackagingComponent", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AdditionInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngredientInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("OrderItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackagingComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("AdditionInternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IngredientInternalId");

                    b.HasIndex("OrderItemDetailsId");

                    b.HasIndex("PackagingComponentId");

                    b.ToTable("OrderItemDetailPackagingComponents");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long?>("CustomDiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomPriceId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("CustomDiscountId")
                        .IsUnique();

                    b.HasIndex("CustomPriceId")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("OrderItemDetails");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailsAddition", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdditionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IngredientInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("OrderItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PackagingComponentInternalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("AdditionId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IngredientInternalId");

                    b.HasIndex("OrderItemDetailsId");

                    b.HasIndex("PackagingComponentInternalId");

                    b.ToTable("OrderItemDetailsAdditions");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailsImage", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("OrderItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("OrderItemDetailsId");

                    b.ToTable("OrderItemDetailsImages");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Purchases.Purchase", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Purchases.PurchaseItem", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsumablePackagingPriceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("ConsumablePackagingPriceId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.Recipe", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeDescriptionItem", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeDescriptionItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RecipeDescriptionItemTypeId");

                    b.HasIndex("RecipeId", "Order")
                        .IsUnique();

                    b.ToTable("RecipeDescriptionItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeDescriptionItemType", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("RecipeDescriptionItemTypes");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeIngredient", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AdditionInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MeasuringId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MeasuringValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PackagingComponentInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalId");

                    b.HasIndex("AdditionInternalId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasuringId");

                    b.HasIndex("PackagingComponentInternalId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Addition", b =>
                {
                    b.HasBaseType("DessertsMakery.Persistence.Models.Essentials.Component");

                    b.HasDiscriminator().HasValue("Addition");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Ingredient", b =>
                {
                    b.HasBaseType("DessertsMakery.Persistence.Models.Essentials.Component");

                    b.HasDiscriminator().HasValue("Ingredient");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.PackagingComponent", b =>
                {
                    b.HasBaseType("DessertsMakery.Persistence.Models.Essentials.Component");

                    b.HasDiscriminator().HasValue("PackagingComponent");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.Consumable", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Component", "Component")
                        .WithMany("Consumables")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackaging", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Consumables.Consumable", "Consumable")
                        .WithMany("ConsumablePackagings")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Measuring", "Measuring")
                        .WithMany("ConsumablePackagings")
                        .HasForeignKey("MeasuringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");

                    b.Navigation("Measuring");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingImage", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Consumables.ConsumablePackaging", "ConsumablePackaging")
                        .WithMany("Images")
                        .HasForeignKey("ConsumablePackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumablePackaging");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingPrice", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Consumables.ConsumablePackaging", "ConsumablePackaging")
                        .WithMany("Prices")
                        .HasForeignKey("ConsumablePackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumablePackaging");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamily", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertFamily", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamilyWeight", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertFamily", "DessertFamily")
                        .WithMany("DessertFamilyWeights")
                        .HasForeignKey("DessertFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertWeight", "DessertWeight")
                        .WithMany("DessertFamilyWeights")
                        .HasForeignKey("DessertWeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DessertFamily");

                    b.Navigation("DessertWeight");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertPricing", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertFamilyWeight", "DessertFamilyWeight")
                        .WithMany("DessertPricing")
                        .HasForeignKey("DessertFamilyWeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DessertFamilyWeight");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertTemplate", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertFamily", null)
                        .WithMany("DessertTemplates")
                        .HasForeignKey("DessertFamilyInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertFamilyWeight", "DessertFamilyWeight")
                        .WithMany("DessertTemplates")
                        .HasForeignKey("DessertFamilyWeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DessertFamilyWeight");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertTemplateRecipe", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertTemplate", "DessertTemplate")
                        .WithMany("DessertTemplateRecipes")
                        .HasForeignKey("DessertTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Recipes.Recipe", "Recipe")
                        .WithMany("DessertTemplateRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DessertTemplate");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertWeight", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Measuring", "Measuring")
                        .WithMany("DessertWeights")
                        .HasForeignKey("MeasuringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measuring");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Component", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Measuring", "Measuring")
                        .WithMany("Components")
                        .HasForeignKey("MeasuringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Component", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Measuring");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.ComponentMeasuringConversion", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Component", "Component")
                        .WithMany("ComponentMeasuringConversions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Measuring", "Measuring")
                        .WithMany("ComponentMeasuringConversions")
                        .HasForeignKey("MeasuringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Measuring");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.Order", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Customers.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Desserts.DessertTemplate", "DessertTemplate")
                        .WithMany("OrderItems")
                        .HasForeignKey("DessertTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "OrderItemDetails")
                        .WithOne("OrderItem")
                        .HasForeignKey("DessertsMakery.Persistence.Models.Orders.OrderItem", "OrderItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DessertTemplate");

                    b.Navigation("Order");

                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailPackagingComponent", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Addition", null)
                        .WithMany("OrderItemDetailPackagingComponents")
                        .HasForeignKey("AdditionInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Ingredient", null)
                        .WithMany("OrderItemDetailPackagingComponents")
                        .HasForeignKey("IngredientInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "OrderItemDetails")
                        .WithMany("PackagingComponents")
                        .HasForeignKey("OrderItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.PackagingComponent", "PackagingComponent")
                        .WithMany("OrderItemDetailPackagingComponents")
                        .HasForeignKey("PackagingComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItemDetails");

                    b.Navigation("PackagingComponent");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Orders.CustomDiscount", "CustomDiscount")
                        .WithOne("OrderItemDetails")
                        .HasForeignKey("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "CustomDiscountId");

                    b.HasOne("DessertsMakery.Persistence.Models.Orders.CustomPrice", "CustomPrice")
                        .WithOne("OrderItemDetails")
                        .HasForeignKey("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "CustomPriceId");

                    b.Navigation("CustomDiscount");

                    b.Navigation("CustomPrice");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailsAddition", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Addition", "Addition")
                        .WithMany("OrderItemDetailsAdditions")
                        .HasForeignKey("AdditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Ingredient", null)
                        .WithMany("OrderItemDetailsAdditions")
                        .HasForeignKey("IngredientInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "OrderItemDetails")
                        .WithMany("Additions")
                        .HasForeignKey("OrderItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.PackagingComponent", null)
                        .WithMany("OrderItemDetailsAdditions")
                        .HasForeignKey("PackagingComponentInternalId");

                    b.Navigation("Addition");

                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetailsImage", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", "OrderItemDetails")
                        .WithMany("OrderItemDetailsImages")
                        .HasForeignKey("OrderItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Purchases.PurchaseItem", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingPrice", "ConsumablePackagingPrice")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ConsumablePackagingPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Purchases.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumablePackagingPrice");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeDescriptionItem", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Recipes.RecipeDescriptionItemType", "RecipeDescriptionItemType")
                        .WithMany("RecipeDescriptionItems")
                        .HasForeignKey("RecipeDescriptionItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeDescriptionItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeDescriptionItemType");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Addition", null)
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("AdditionInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.Measuring", "Measuring")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("MeasuringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DessertsMakery.Persistence.Models.Essentials.PackagingComponent", null)
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("PackagingComponentInternalId");

                    b.HasOne("DessertsMakery.Persistence.Models.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Measuring");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.Consumable", b =>
                {
                    b.Navigation("ConsumablePackagings");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackaging", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Consumables.ConsumablePackagingPrice", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Customers.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamily", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DessertFamilyWeights");

                    b.Navigation("DessertTemplates");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertFamilyWeight", b =>
                {
                    b.Navigation("DessertPricing");

                    b.Navigation("DessertTemplates");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertTemplate", b =>
                {
                    b.Navigation("DessertTemplateRecipes");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Desserts.DessertWeight", b =>
                {
                    b.Navigation("DessertFamilyWeights");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Component", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ComponentMeasuringConversions");

                    b.Navigation("Consumables");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Measuring", b =>
                {
                    b.Navigation("ComponentMeasuringConversions");

                    b.Navigation("Components");

                    b.Navigation("ConsumablePackagings");

                    b.Navigation("DessertWeights");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.CustomDiscount", b =>
                {
                    b.Navigation("OrderItemDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.CustomPrice", b =>
                {
                    b.Navigation("OrderItemDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Orders.OrderItemDetails", b =>
                {
                    b.Navigation("Additions");

                    b.Navigation("OrderItem")
                        .IsRequired();

                    b.Navigation("OrderItemDetailsImages");

                    b.Navigation("PackagingComponents");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Purchases.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.Recipe", b =>
                {
                    b.Navigation("DessertTemplateRecipes");

                    b.Navigation("RecipeDescriptionItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Recipes.RecipeDescriptionItemType", b =>
                {
                    b.Navigation("RecipeDescriptionItems");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Addition", b =>
                {
                    b.Navigation("OrderItemDetailPackagingComponents");

                    b.Navigation("OrderItemDetailsAdditions");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.Ingredient", b =>
                {
                    b.Navigation("OrderItemDetailPackagingComponents");

                    b.Navigation("OrderItemDetailsAdditions");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DessertsMakery.Persistence.Models.Essentials.PackagingComponent", b =>
                {
                    b.Navigation("OrderItemDetailPackagingComponents");

                    b.Navigation("OrderItemDetailsAdditions");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
